### NumPy
NumPy (Numerical Python) is a Python library that includes a multidimensional array object, various derived objects, and a collection of routines for performing fast array operations.

In [1]:
#import NumPy

import numpy as np

In [2]:
#checking NumPy version

print(np.__version__)

1.26.4


In [3]:
#creating a NumPy array with a list

arr = np.array(["strawberry", "blueberry", "cherry", "cranberry", "blackberry"])

print(arr)

print(type(arr))

['strawberry' 'blueberry' 'cherry' 'cranberry' 'blackberry']
<class 'numpy.ndarray'>


In [4]:
#use a tuple to create a NumPy array

arr = np.array(("strawberry", "blueberry", "cherry", "cranberry", "blackberry"))

print(arr)

print(type(arr))

['strawberry' 'blueberry' 'cherry' 'cranberry' 'blackberry']
<class 'numpy.ndarray'>


## DIMENSION

NumPy's primary object is a homogenous multidimensional array. It is a table with elements (typically numbers) of the same type, each indexed by a non-negative integer tuple. In NumPy, dimensions are referred to as axes.ay

In [5]:
#0-D array

arr = np.array(13)

print(arr)

13


In [6]:
#create a 1-D array

arr = np.array([11, 12, 13])

print(arr)

[11 12 13]


In [7]:
#create a 2-D array containing two arrays

arr = np.array([[8,9,10], [11, 12, 13], [14, 15, 16]])

print(arr)

[[ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [8]:
#create a 3-D array with 2-D arrays, both containing two arrays

arr = np.array([[[8,9,10], [11, 12, 13]], [[8,9,10], [11, 12, 13]]])

print(arr)

[[[ 8  9 10]
  [11 12 13]]

 [[ 8  9 10]
  [11 12 13]]]


Check how many dimensions the arrays have

In [9]:
a = np.array(13)
b = np.array([11, 12, 13])
c = np.array([[8,9,10], [11, 12, 13], [14, 15, 16]])
d = np.array([[[8,9,10], [11, 12, 13]], [[8,9,10], [11, 12, 13]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [10]:
#notes: ndim represents the number of dimensions (axes) of the ndarray.

In [11]:
#create an array with 5 dimensions and verify that it has 5 dimensions

arr = np.array([10, 11, 12, 13], ndmin=5)

print(arr)
print('number of dimensions:', arr.ndim)

[[[[[10 11 12 13]]]]]
number of dimensions: 5


In [12]:
#try to change the dimension into other dimensions
arr = np.array([[8,9,10], [11, 12, 13], [14, 15, 16]], ndmin=3)

print(arr)
print('number of dimensions:', arr.ndim)

[[[ 8  9 10]
  [11 12 13]
  [14 15 16]]]
number of dimensions: 3


In [13]:
#get the first element from the following array

arr = np.array([10, 11, 12, 13])

print(arr[0])

10


In [14]:
#get the second element from the following array

arr = np.array([10, 11, 12, 13])

print(arr[1])

11


In [15]:
#get the third and fourth element from the following array

arr = np.array([10, 11, 12, 13])

print(arr[2] + arr[3])

25


In [16]:
#get element
arr = np.array([[8,9,10], [11, 12, 13], [14, 15, 16]])

In [17]:
#access the element on the first row, second column

arr = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

print('2nd element on 1st row:', arr[0,1])

2nd element on 1st row: 12


In [18]:
#access the element on the second row, fifth column

arr = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

print('5th element on 2nd row:', arr[1,4])

5th element on 2nd row: 20


In [19]:
#access the third element of the second array of the first array

arr = np.array([[[8,9,10], [11, 12, 13]], [[1,2,3], [4, 5, 6]]])

print(arr[1, 0, 2])

3


In [20]:
arr = np.array([[[8,9,10], [11, 12, 13]], [[1,2,3], [4, 5, 6]]])

print(arr)

[[[ 8  9 10]
  [11 12 13]]

 [[ 1  2  3]
  [ 4  5  6]]]


The Details:

In [21]:
arr = np.array([[[8,9,10], [11, 12, 13]], [[1,2,3], [4, 5, 6]]])

print(arr[0, 1, 1])

#dim 0 = [[8,9,10], [11, 12, 13]], [[1,2,3], [4, 5, 6]]
#row 1 = [11, 12, 13]]
#element 2 = 12

12
